[package]
name = "tachyon"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "The Tachyon shielded transaction protocol (stub)"
readme = "README.md"
repository = "https://github.com/turbocrime/tachyon"
categories = ["cryptography::cryptocurrencies"]
keywords = ["zcash", "tachyon"]

[dependencies]
bitvec = "1.0.1"
core2 = { version = "0.4.0", default-features = false, features = ["alloc"] }
blake2b_simd.workspace = true
ff.workspace = true
pasta_curves.workspace = true
ragu_arithmetic.workspace = true
ragu_circuits.workspace = true
ragu_core.workspace = true
ragu_gadgets.workspace = true
ragu_pasta.workspace = true
ragu_pcd.workspace = true
ragu_primitives.workspace = true
rand.workspace = true
reddsa = "0.5.1"

[dev-dependencies]
proptest.workspace = true

[lints]
workspace = true

[lib]
bench = false

[features]
default = ["std"]
std = ["core2/std"]
