edition = "2024"

use_field_init_shorthand = true
use_try_shorthand = true

reorder_imports = true
reorder_modules = true

# Unstable reorder options
unstable_features = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"

