edition = "2024"

newline_style = "Unix"

match_arm_leading_pipes = "Always"
match_block_trailing_comma = true
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
use_field_init_shorthand = true
use_try_shorthand = true

merge_derives = true

force_explicit_abi = true

# cargo +nightly fmt
required_version = "1.8.0"
unstable_features = true

group_imports = "StdExternalCrate"
imports_granularity = "Crate"

reorder_impl_items = true

format_code_in_doc_comments = true
normalize_comments = true
normalize_doc_attributes = true
wrap_comments = true

format_macro_matchers = true

force_multiline_blocks = true

condense_wildcard_suffixes = true
